# Generated by Django 3.1.5 on 2021-01-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0002_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
