# Generated by Django 3.1.5 on 2021-01-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0003_deck_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='description',
        ),
    ]
