# Generated by Django 3.1.5 on 2021-01-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0004_remove_deck_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('notes', models.TextField(max_length=300)),
            ],
        ),
    ]
