# Generated by Django 3.1.5 on 2021-01-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0005_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashapp.deck'),
            preserve_default=False,
        ),
    ]
