# Generated by Django 3.1 on 2021-02-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0006_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
